# Generated by Django 3.0.3 on 2020-03-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
